backend:
  name: git-gateway
  branch: main
  repo: DreamEmulator/parsimony.dev
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
site_url: https://parsimony.dev
display_url: https://parsimony.dev

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - label: Toolbox
    name: Toolbox
    folder: "content/tools/"
    extension: "mdx"
    format: "frontmatter"
    summary: "{{tool}}"
    create: true
    label_singular: Tool
    fields:
      - name: Title
        widget: string
      - name: Body
        widget: string
      - name: Link
        widget: object
        fields:
          - name: Title
            widget: string
            required: false
          - name: URL
            widget: string
            required: false

  - name: "pages"
    label: "Pages"
    files:
      - name: home
        label: "Home"
        file: "site/content/home.yml"
        fields:
          - name: Banner
            widget: object
            summary: "{{fields.slogan}} - {{fields.pitch}}"
            fields:
            - name: Slogan
              widget: string
              required: false
            - name: Pitch
              widget: string
              required: false
            - name: Link
              widget: object
              fields:
              - name: Title
                widget: string
                required: false
              - name: URL
                widget: string
                required: false
          - name: Values
            widget: object
            fields:
              - name: What
                widget: object
                fields:
                  - name: Title
                    widget: string
                    required: false
                  - name: Body
                    widget: string
                    required: false
                  - name: Link
                    widget: object
                    fields:
                      - name: Title
                        widget: string
                        required: false
                      - name: URL
                        widget: string
                        required: false
              - name: Why
                widget: object
                fields:
                  - name: Title
                    widget: string
                    required: false
                  - name: Body
                    widget: string
                    required: false
                  - name: Link
                    widget: object
                    fields:
                      - name: Title
                        widget: string
                        required: false
                      - name: URL
                        widget: string
                        required: false
              - name: How
                widget: object
                fields:
                  - name: Title
                    widget: string
                    required: false
                  - name: Body
                    widget: string
                    required: false
                  - name: Link
                    widget: object
                    fields:
                      - name: Title
                        widget: string
                        required: false
                      - name: URL
                        widget: string
                        required: false
          - name: Definition
            widget: object
            fields:
              - name: Word
                widget: string
                required: false
              - name: Definition
                widget: string
                required: false
          - name: Skills
            widget: object
            fields:
              - name: CTA
                widget: object
                fields:
                  - name: Title
                    widget: string
                  - name: Link
                    widget: string
                  - name: URL
                    widget: string
              - name: Skills
                widget: object
                fields:
                  - name: First
                    widget: object
                    fields:
                      - name: Title
                        widget: string
                      - name: Body
                        widget: string
                  - name: Second
                    widget: object
                    fields:
                      - name: Title
                        widget: string
                      - name: Body
                        widget: string
                  - name: Third
                    widget: object
                    fields:
                      - name: Title
                        widget: string
                      - name: Body
                        widget: string
                  - name: Fourth
                    widget: object
                    fields:
                      - name: Title
                        widget: string
                      - name: Body
                        widget: string
          - name: Testimonials
            widget: list
            fields:
              - name: Name
                widget: string
              - name: Role
                widget: string
              - name: Image
                widget: string
              - name: Text
                widget: string
          - name: Strategy
            widget: object
            summary: "{{fields.title}}"
            fields:
              - name: Title
                widget: string
                required: false
              - name: Steps
                widget: list
                label_singular: Step
                fields:
                  - name: Title
                    widget: string
                  - name: Body
                    widget: string
